### ISSUE TITLE
Initalizing a new plugin with V.2.0.5 fails because tsconfig-build.json is missing

### ISSUE THREAD

**Issue by orr3** [tobua/create-react-native-plugin#2]
`# npx create-react-native-plugin react-native-my-plugin`

```
node:fs:599
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open '/workspaces/react-native-my-plugin/tsconfig-build.json'
    at Object.openSync (node:fs:599:3)
    at readFileSync (node:fs:467:35)
    at replaceTemplateVariables (file:///root/.npm/_npx/c8e08ff0fcfedc7f/node_modules/create-react-native-plugin/customize.js:21:20)
    at Array.forEach (<anonymous>)
    at default (file:///root/.npm/_npx/c8e08ff0fcfedc7f/node_modules/create-react-native-plugin/customize.js:29:9)
    at file:///root/.npm/_npx/c8e08ff0fcfedc7f/node_modules/create-react-native-plugin/index.js:39:1
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async loadESM (node:internal/process/esm_loader:85:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/workspaces/react-native-my-plugin/tsconfig-build.json'
}
```

Changing to release 2.0.4 seems to do the trick: `npx create-react-native-plugin@2.0.4 react-native-my-plugin`.

**Comment by tobua** [comment]
Thanks for reporting. Missed to adapt that after the last change and never tested it afterwards unfortunately. That list shouldn't be hardcode anyways ;) but I did that a long time ago.

Let me know if you run into any other issues.

**Comment by tobua** [comment]
Hold on a second, still requires another release, seems like there's another issues as `.gitignore` isn't copied over.

**Comment by tobua** [comment]
Just ran 2.0.7 without any issues.

Good luck with your plugin!
